### ISSUE TITLE
Force Stopped After Tapping "Open Device Notification Settings"

### ISSUE THREAD

**Issue by zputnyq** [TylerWilliamson/BatteryNotification#2]
Thank you.
This app is beautiful & I believe it will be great in the future.
I really appriciate it.

As the title said there is an issue, after tapping Open Device Notification Settings.

I'm using Xperia M4 (stock android 6.0.1)
Battery Notification v 1.4.2 (F - droid)
Here, I attached the log

[logcat_04-20-2022_00-11-35.txt](https://github.com/TylerWilliamson/BatteryNotification/files/8515127/logcat_04-20-2022_00-11-35.txt)

**Comment by TylerWilliamson** [comment]
I will investigate this issue and I hope to address it in the nwxt release

**Comment by TylerWilliamson** [comment]
I believe I have fixed this in [Version 1.4.3](https://github.com/TylerWilliamson/BatteryNotification/releases/tag/1.4.3). This version is available on GitHub, on Google Play Store for open beta testers, and on F-Droid when they next update their repo. Please test and let me know if you are able to replicate your issue. Otherwise, I will close the issue in about a week. Thanks!

**Comment by zputnyq** [comment]
> I believe I have fixed this in [Version 1.4.3](https://github.com/TylerWilliamson/BatteryNotification/releases/tag/1.4.3). This version is available on GitHub, on Google Play Store for open beta testers, and on F-Droid when they next update their repo. Please test and let me know if you are able to replicate your issue. Otherwise, I will close the issue in about a week. Thanks!

Yes, it's fix in v 1.4.3. I tested it
Thank you.
